### ISSUE TITLE
Rsync specify ssh key

### ISSUE THREAD

**Issue by drgroot** [mattijs/node-rsync#32]
How would one specify the ssh key using this tool?

**Comment by mattijs** [comment]
You can use the rsync `rsh` option to specify the remote shell to use:

```
rsync --rsh="ssh -i ~/.ssh/identity_file" ...
```

Since node-rsync is just a wrapper that spits out rsync commands this is the equivalent:

```javascript
var cmd = (new Rsync())
    .set('rsh', 'ssh -i ~/.ssh/identity_file');
```

or use the `shell` shortcut:

```javascript
var cmd = Rsync.build({
  'shell': "ssh -i ~/.ssh/identity_file",
  // ... other options below
});
```
Alternatively you can also set this up outside of node-resync as an identity in your ssh config file. See this [StackOverflow post](http://stackoverflow.com/a/5527157) for more details.
