### ISSUE TITLE
OnProgress event

### ISSUE THREAD

**Issue by gpapin** [mattijs/node-rsync#49]
Is there a way to have an event handeler hooked on the progress ?
I need to log the current progress/ speed of a given job every seconds

**Comment by mattijs** [comment]
There is no dedicated progress events coming from the `rsync` command that is executed under the hood. This is just a basic unix command.

You can however hook into the `stdout` and `stderr`streams that come from the executed command. See the [output](https://github.com/mattijs/node-rsync#outputstdouthandler-stderrhandler) documentation in the README for more information.

The two functions that you can register as output handlers receive the stdout and stderr output as streams but you have to parse the output yourself to get the progress/speed of the job. Make sure to also set the `progress` flag for the command otherwise progress won't be reported on `stdout`.

You can experiment setting the `progress` flag or use `--info=progress2` to get the output. Trying `--no-inc-recursive` might also help getting accurate progress output, see [here](http://stackoverflow.com/questions/7157973/monitoring-rsync-progress)
